import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type LanguageCode = 'en' | 'ru';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard',
    'configuration': 'Configuration',
    'logout': 'Logout',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'loading': 'Loading...',
    'help': 'Help',
    'copyright': 'Copyright © 2024 CZ Holding. All rights reserved.',
    'logged_out': 'Logged out',
    'successfully_logged_out': 'You have been successfully logged out.',
    'welcome_back': 'Welcome back!',
    'successfully_logged_in': 'You have successfully logged in.',
    'admin_panel': 'Admin Panel',
    'enter_credentials': 'Enter your credentials to access the system',
    'username': 'Username',
    'password': 'Password',
    'login': 'Login',
    'logging_in': 'Logging in...',
    'login_failed': 'Login failed',
    'invalid_credentials': 'Invalid credentials',
    'overview': 'Overview of your WordPress translation automation',
    'getting_started': 'Getting Started',
    'configure_wp': '1. Configure WordPress Connection',
    'configure_wp_desc': 'Go to Configuration page and set up your WordPress URL, credentials, and target languages.',
    'select_posts': '2. Select Posts to Translate',
    'select_posts_desc': 'Navigate to Posts Management to view your WordPress posts and select which ones to translate.',
    'monitor_progress_help': '3. Monitor Translation Progress',
    'monitor_progress_desc': 'Track your translation jobs in real-time on the Translation Jobs page.',
    'translation_jobs_page': 'Translation Jobs',
    'monitor_translations': 'Monitor your translation tasks in real-time and publish completed translations to WordPress',
    'app_tagline': 'Automate WordPress content translation with Google Gemini AI and publish directly to Polylang',
    'no_jobs': 'No translation jobs yet',
    'start_translation': 'Start by selecting posts to translate in Posts Management.',
    'publish_to_wordpress': 'Publish to WordPress',
    'publish_success': 'Content published to WordPress',
    'publish_failed': 'Publish failed',
    'created': 'Created',
    'updated': 'Updated',
    'progress': 'Progress',
    'tokens': 'tokens',
    'completed_status': 'Completed',
    'processing_status': 'Processing',
    'pending_status': 'Pending',
    'failed_status': 'Failed',
    'configuration_title': 'Configuration',
    'configuration_desc': 'Configure WordPress connection and translation settings',
    'wordpress_connection': 'WordPress Connection',
    'wordpress_connection_desc': 'Configure your WordPress site URL and admin credentials',
    'wordpress_url': 'WordPress URL',
    'wordpress_url_placeholder': 'https://example.com',
    'wordpress_username': 'WordPress Username',
    'wordpress_username_placeholder': 'admin or app password user',
    'admin_password': 'Admin Password',
    'admin_password_desc': 'Application Password from WordPress',
    'test_connection': 'Test Connection',
    'testing': 'Testing...',
    'connection_success': 'Connection successful',
    'connection_failed': 'Connection failed',
    'translation_settings': 'Translation Settings',
    'source_language': 'Source Language',
    'target_languages': 'Target Languages',
    'select_target_languages': 'Select which languages to translate your content to',
    'gemini_api': 'Google Gemini API',
    'gemini_api_desc': 'Configure your Gemini API key for translation',
    'gemini_api_key': 'Gemini API Key',
    'gemini_api_key_placeholder': 'Enter your API key',
    'system_instruction': 'System Instruction',
    'system_instruction_desc': 'Custom instruction for the AI translator',
    'unsaved_changes': 'Unsaved changes',
    'save_settings': 'Save Settings',
    'saving': 'Saving...',
    'settings_saved': 'Settings saved',
    'settings_saved_desc': 'Your configuration has been updated successfully.',
    'save_failed': 'Save failed',
    'polylang_setup': 'Polylang Setup',
    'check_polylang_status': 'Check Polylang Status',
    'polylang_status': 'Polylang Status',
    'polylang_info': 'Verify that Polylang plugin is installed and activated on your WordPress site',
    'checking': 'Checking...',
  },
  ru: {
    'dashboard': 'Панель управления',
    'translation_jobs': 'Задания перевода',
    'configuration': 'Конфигурация',
    'configuration_title': 'Конфигурация',
    'configuration_desc': 'Настройте подключение WordPress и параметры перевода',
    'wordpress_connection': 'Подключение WordPress',
    'wordpress_connection_desc': 'Настройте URL вашего сайта WordPress и учетные данные администратора',
    'wordpress_url': 'URL WordPress',
    'wordpress_url_placeholder': 'https://example.com',
    'wordpress_username': 'Имя пользователя WordPress',
    'wordpress_username_placeholder': 'admin или пользователь пароля приложения',
    'admin_password': 'Пароль администратора',
    'admin_password_desc': 'Пароль приложения из WordPress',
    'test_connection': 'Проверить подключение',
    'testing': 'Проверка...',
    'connection_success': 'Подключение успешно',
    'connection_failed': 'Ошибка подключения',
    'translation_settings': 'Параметры перевода',
    'source_language': 'Исходный язык',
    'target_languages': 'Целевые языки',
    'select_target_languages': 'Выберите языки, на которые нужно переводить контент',
    'gemini_api': 'API Google Gemini',
    'gemini_api_desc': 'Настройте ключ API Gemini для перевода',
    'gemini_api_key': 'Ключ API Gemini',
    'gemini_api_key_placeholder': 'Введите ваш ключ API',
    'system_instruction': 'Системная инструкция',
    'system_instruction_desc': 'Пользовательская инструкция для AI переводчика',
    'unsaved_changes': 'Несохраненные изменения',
    'save_settings': 'Сохранить параметры',
    'saving': 'Сохранение...',
    'settings_saved': 'Параметры сохранены',
    'settings_saved_desc': 'Ваша конфигурация успешно обновлена.',
    'save_failed': 'Ошибка сохранения',
    'polylang_setup': 'Установка Polylang',
    'check_polylang_status': 'Проверить статус Polylang',
    'polylang_status': 'Статус Polylang',
    'polylang_info': 'Убедитесь, что плагин Polylang установлен и активирован на вашем сайте WordPress',
    'checking': 'Проверка...',
    'logout': 'Выход',
    'light_mode': 'Светлая тема',
    'dark_mode': 'Темная тема',
    'loading': 'Загрузка...',
    'help': 'Справка',
    'copyright': 'Авторские права © 2025 CZ Holding. Все права защищены.',
    'logged_out': 'Вы вышли',
    'successfully_logged_out': 'Вы успешно вышли из системы.',
    'welcome_back': 'Добро пожаловать!',
    'successfully_logged_in': 'Вы успешно вошли в систему.',
    'admin_panel': 'Панель администратора',
    'enter_credentials': 'Введите ваши учетные данные для доступа к системе',
    'username': 'Имя пользователя',
    'password': 'Пароль',
    'login': 'Войти',
    'logging_in': 'Вход...',
    'login_failed': 'Ошибка входа',
    'invalid_credentials': 'Неверные учетные данные',
    'overview': 'Обзор автоматизации перевода контента WordPress',
    'getting_started': 'Начало работы',
    'configure_wp': '1. Настройте подключение WordPress',
    'configure_wp_desc': 'Перейдите на страницу конфигурации и установите URL WordPress, учетные данные и целевые языки.',
    'select_posts': '2. Выберите посты для перевода',
    'select_posts_desc': 'Перейдите в раздел управления постами, чтобы просмотреть ваши посты WordPress и выбрать те, которые нужно перевести.',
    'monitor_progress_help': '3. Отслеживайте прогресс перевода',
    'monitor_progress_desc': 'Отслеживайте задания перевода в реальном времени на странице заданий перевода.',
    'dashboard_title': 'Панель управления',
    'total_posts': 'Всего постов',
    'total_posts_desc': 'Посты WordPress',
    'translated_posts': 'Переведено',
    'translated_posts_desc': 'Завершенные переводы',
    'pending_jobs': 'Незавершенные',
    'pending_jobs_desc': 'В очереди',
    'tokens_used': 'Токены использованы',
    'tokens_used_desc': 'Токены API Gemini',
    'posts_management': 'Управление контентом',
    'posts_management_desc': 'Выберите посты и страницы для перевода',
    'content_type': 'Тип контента',
    'posts': 'Посты',
    'pages': 'Страницы',
    'all_content': 'Всё',
    'import_content': 'Импортировать контент',
    'importing': 'Импортирование...',
    'no_content_found': 'Контент не найден. Настройте подключение WordPress.',
    'translate_selected': 'Перевести выбранное',
    'select_all': 'Выбрать всё',
    'id_col': 'ID',
    'title_col': 'Заголовок',
    'type_col': 'Тип',
    'status_col': 'Статус',
    'actions_col': 'Действия',
    'translated': 'Переведено',
    'source': 'Источник',
    'missing_lang': 'Язык не установлен',
    'edit_translation': 'Редактировать перевод',
    'manual_translate': 'Перевести вручную',
    'make_corrections': 'Внесите исправления в переведенный контент',
    'post_title': 'Заголовок поста',
    'content': 'Контент',
    'cancel': 'Отмена',
    'save_changes': 'Сохранить',
    'edit': 'Редактировать',
    'polylang_check': 'Проверка Polylang',
    'polylang_required': 'Polylang не установлен',
    'install_polylang': 'Пожалуйста, установите плагин Polylang на вашем WordPress сайте',
    'polylang_active': 'Polylang активен',
    'polylang_languages': 'Языков установлено',
    'check_polylang': 'Проверить Polylang',
    'auto_translate': 'Автоматический перевод',
    'translate_with_ai': 'Перевести с использованием AI',
    'translating': 'Перевод...',
    'edit_and_review': 'Редактировать и проверить',
    'page': 'Страница',
    'post': 'Пост',
    'pagination': 'Страница {current} из {total}',
    'monitor_progress': 'Отслеживайте задания перевода в реальном времени',
    'no_jobs': 'Нет заданий перевода',
    'start_translation': 'Начните с выбора контента для перевода в разделе Управления контентом',
    'publish_to_wordpress': 'Опубликовать в WordPress',
    'published': 'Опубликовано',
    'publishing': 'Публикация...',
    'publish_success': 'Контент опубликован в WordPress',
    'publish_failed': 'Ошибка публикации',
    'created': 'Создано',
    'updated': 'Обновлено',
    'progress': 'Прогресс',
    'tokens': 'токены',
    'translation_jobs_page': 'Задания перевода',
    'monitor_translations': 'Отслеживайте ваши задания перевода в реальном времени',
    'app_tagline': 'Автоматизируйте перевод контента WordPress с помощью Google Gemini AI и публикуйте напрямую в Polylang',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const stored = localStorage.getItem('wp-polylingo-language') as LanguageCode;
    return stored || 'en';
  });

  useEffect(() => {
    localStorage.setItem('wp-polylingo-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageState, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
